# Site settings
title: Ofiste Değilim
header-img: img/home-bg.jpg
email: denizemirgullari@gmail.com
description: "Ofisler dünyasını bırakmış, kendini hayallerine adamış bir kadın."
baseurl: ""
url: "http://ofistedegilim.com"
twitter_username: d_emirogullari
facebook_username:  denizemirogullari
timezone: Europe/Istanbul

# Build settings
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

kramdown:
  input: GFM

gems: [jekyll-paginate]
